'use strict';

// GA4本体の読み込み前でも、意味のある完了イベントだけを安全にキューへ積む
export const ANALYTICS = {
    track(eventName, params = {}) {
        if (!/^[a-z][a-z0-9_]{0,39}$/.test(eventName)) return;
        window.dataLayer = window.dataLayer || [];
        window.gtag = window.gtag || function gtag() {
            window.dataLayer.push(arguments);
        };
        window.gtag('event', eventName, params);
    },
    markEngaged() {
        if (typeof window.dispatchEvent === 'function' && typeof window.CustomEvent === 'function') {
            window.dispatchEvent(new CustomEvent('playpoint:engaged'));
        }
    }
};

export const CONSTANTS = {
    MODE_MAIN: 'main',
    MODE_REVERSE: 'reverse',
    MODE_DIARY: 'diary',
    CLASS_VISIBLE: 'visible',
    CLASS_HAS_RESULT: 'has-result',
    CLASS_ACTIVE: 'active',
    CLASS_HIDDEN: 'hidden',
    SELECTOR_INFO_BTN: '.info-btn',
    SELECTOR_TOOLTIP_BOX: '.tooltip-box',
    DIARY_DATA_KEY: 'hokuhokuDiaryData',
    SAVE_CONFIRMATION_DURATION: 1500,
    STORAGE_REGION_KEY: 'playpointPreferredRegion'
};

export const CONFIGS = {
    'JP': {
        lang: "ja",
        statuses: { "ブロンズ": 1.0, "シルバー": 1.25, "ゴールド": 1.5, "プラチナ": 1.75, "ダイヤモンド": 2.0 },
        statusRates: { 1.0: 1.0, 1.25: 1.25, 1.5: 1.5, 1.75: 1.75, 2.0: 2.0 },
        thresholds: { "シルバー": 250, "ゴールド": 1000, "プラチナ": 4000, "ダイヤモンド": 15000 },
        statusPointsMapping: { 1.0: ["シルバー", "ゴールド", "プラチナ", "ダイヤモンド"], 1.25: ["ゴールド", "プラチナ", "ダイヤモンド"], 1.5: ["プラチナ", "ダイヤモンド"], 1.75: ["ダイヤモンド"], 2.0: [] },
        currencySymbol: "円",
        rateUnit: "100円",
        tooltips: {
            'tooltip-current-status': `<strong>【現在のステータスの確認方法】</strong><ol><li>Google Play ストアを開きます。</li><li>右上のプロフィールアイコンをタップします。</li><li>「Play ポイント」を選択します。</li></ol><hr><p>※ステータスに応じて、基本還元率は自動で入力されます。</p>`,
            'tooltip-target-status': `<strong>【各ステータスの達成条件】</strong><ul><li><strong>シルバー:</strong> 250 pt 以上</li><li><strong>ゴールド:</strong> 1,000 pt 以上</li><li><strong>プラチナ:</strong> 4,000 pt 以上</li><li><strong>ダイヤモンド:</strong> 15,000 pt 以上</li></ul><hr><p>※ポイントは毎年1月1日〜12月31日の1年間で累積され、目標ポイントに達した時点で即座にランクアップします（有効期限は翌年末まで）。</p>`,
            'tooltip-needed-points': `<strong>【必要ポイントの確認方法】</strong><ol><li>Google Play ストアの「Play ポイント」画面を開きます。</li><li>画面に表示される「次のステータスまであと◯◯ pt」という部分の数字を、そのまま入力してください。</li></ol><hr><p>※Playポイントのランク判定期間は毎年12月31日までです。そのため、計算結果の「月平均」は12月末までの残り月数で均等に割り出した目安となります。</p>`,
            'tooltip-base-rate': `<strong>【基本還元ポイントについて】</strong><p>現在のステータスに応じた、基本の還元率が自動で入力されます。</p><p><strong>特定のアプリ限定のポイント増量キャンペーン</strong>などを利用する場合は、こちらの数値を直接編集してください。</p><hr><p><strong>※ご注意</strong><br>この値と「キャンペーン倍率」で計算した値を比較し、<strong>よりお得な方</strong>が計算に自動で適用されます。</p>`,
            'tooltip-multiplier': `<strong>【キャンペーン倍率について】</strong><p>週末などに開催される、ポイント増量キャンペーンの倍率を入力します。</p><p>例：ゴールド(1.5pt) × <strong>3倍</strong> = 4.5pt</p><hr><p><strong>※ご注意</strong><br>この倍率で計算した値と「基本還元ポイント」の入力値を比較し、<strong>よりお得な方</strong>が計算に自動で適用されます。</p>`,
            'tooltip-amount-yen': `<strong>【獲得ポイントを計算】</strong><p>入力した金額で、どれくらいのポイントが獲得できるかをシミュレーションします。</p>`,
            'tooltip-reverse-status': `<strong>【ステータスごとの基本還元率】</strong><ul><li><strong>ブロンズ:</strong> 1.0 pt / 100円</li><li><strong>シルバー:</strong> 1.25 pt / 100円</li><li><strong>ゴールド:</strong> 1.5 pt / 100円</li><li><strong>プラチナ:</strong> 1.75 pt / 100円</li><li><strong>ダイヤモンド:</strong> 2.0 pt / 100円</li></ul>`
        },
        uiText: {
            title: "Playポイント計算機 - Play Point Calculator | あといくらでレベルアップ？", mainTitle: "Playポイント計算機",
            siteDescription: "現在のステータスから目標達成までの必要課金額の計算ができます！<br>さらに課金額から獲得できるポイントも計算できます！",
            tabMain: "通常計算", tabReverse: "逆算モード", tabDiary: "ほくほくリワード日記",
            sectionTitleStatus: "ステータス入力", labelCurrentStatus: "現在のステータス",
            labelTargetStatus: "目標ステータス", labelNeededPoints: "目標までの必要ポイント",
            neededPointsPlaceholder: "例：1728", sectionTitleRate: "還元設定",
            labelBaseRate: "100円あたりの基本還元ポイント", labelMultiplier: "キャンペーン倍率（例：3倍）", labelMultiplierReverse: "キャンペーン倍率",
            warningRate: "※ ポイント増量/倍率について:<br>計算時、入力値と(ステータス×倍率)を比較し、より有利な方が自動適用されます (併用不可)",
            calculateButton: "課金額を計算", copyButton: "コピーする", tweetButton: "結果をXでシェア",
            sectionTitleReverse: "逆算モード", labelAmountYen: "課金額（円）",
            amountYenPlaceholder: "例：5000", reverseCalculateButton: "ポイントを計算",
            nextTargetNone: "次の目標はありません", errorInput: "有効な数値を入力し、目標ステータスを選択してください",
            errorNeededPoints: "目標までの必要ポイントに有効な数値を入力してください",
            errorTargetStatus: "目標ステータスを選択してください",
            errorRate: "計算に使用する還元率が0以下です", errorMonth: "年内の残り期間の計算に失敗しました（現在12月、またはシステム時刻をご確認ください）",
            errorInputReverse: "有効な数値を入力してください", errorRateReverse: "計算に使用する還元率が0以下です",
            errorTargetConsistency: "入力した必要ポイントが、選択した目標ステータスに対して不正です。値を確認してください。",
            resultLabelNeededPoints: "目標までの必要ポイント", resultLabelTotalYen: "合計の必要課金額目安",
            resultLabelMonthlyYen: "月平均目安", resultLabelMonths: "ヶ月",
            resultLabelRate: "適用還元率", resultLabelEarnedPoints: "獲得ポイント予測",
            perMonth: "/月",
            calculationNote: "※Google Playポイントのランク集計期間（毎年12月31日）までの残り <b>{months}ヶ月</b> で均等に割り出した目標課金額の目安です。",
            yearSuffix: "年", monthNames: ["１月", "２月", "３月", "４月", "５月", "６月", "７月", "８月", "９月", "１０月", "１１月", "１２月"],
            weekLabel: "第", weekSuffix: "週", pointsPlaceholder: "ポイント", saveButton: "保存",
            monthlySummaryTitle: "月間集計", yearlySummaryTitle: "年間集計",
            totalLabel: "合計:", averageLabel: "平均:", pointsUnit: "pt", perWeekUnit: "pt/週",
            guestNotice: "【！】現在、この日記の記録はブラウザ内にのみ保存されます。ブラウザのキャッシュ削除や閲覧データ削除で記録が消えてしまうのでご注意ください。※将来的にサーバー側に記録を保存できる会員機能も検討中です！ご期待ください！",
            prizeOptions: ["景品なし", "マウス", "イヤホン", "その他"],
            noWeeksMessage: "この月には対象となる週がありません。",
            backupTitle: "データのバックアップ・復元",
            exportBtn: "データを書き出す (コピー)",
            importBtn: "データを読み込む (復元)",
            confirmImportBtn: "復元を実行",
            backupPlaceholder: "ここに書き出したデータを貼り付けてください",
            exportSuccess: "日記データをクリップボードにコピーしました！安全な場所に保存してください。",
            importSuccess: "日記データを復元しました！",
            importError: "データのインポートに失敗しました。正しいデータ形式か確認してください。",
            fridayReminderText: "今日は金曜日！今週のウィークリーリワードを引いて日記に記録しましょう！",
            reminderTitle: "金曜リワード通知（カレンダー登録）",
            reminderDesc: "毎週金曜日にウィークリーリワードを通知するリマインダーを登録できます。リワードの引き忘れを防いで、日記への記録を習慣化しましょう！",
            btnGoogleCal: "Google カレンダーに登録",
            btnICal: "カレンダーアプリ（iCal）登録",
            linkArticles: { text: "📝 記事一覧", href: "blog/" },
            linkKatakata: { text: "🧪 KatakataLab", href: "https://katakatalab.com/" },
            linkPrivacy: { text: "プライバシーポリシー", href: "privacy.html" },
            linkTerms: { text: "利用規約", href: "terms.html" },
            linkQA: { text: "Q&A・あとがき", href: "info.html" },
            linkFeedback: { text: "ご意見・ご感想", href: "https://docs.google.com/forms/d/e/1FAIpQLSe0HDPLt-jfNXuiGmJ3gxlxUtgeGJ5-AM16Bz2yNw5bk3irNw/viewform?usp=dialog" },
            linkAbout: { text: "Playポイントとは？", href: "about-playpoints.html" },
            linkDiscount: { text: "💡 お得に課金する", href: "articles/2026-06-20-discount-gift-cards.html" },
            linkAuthor: { text: "運営者・検証方針", href: "author/katakata.html" },
            linkAttention: { text: "⚠️ 国別差異", href: "attention.html" },
            toastCopySuccess: "クリップボードにコピーしました！",
            toastCopyError: "コピーに失敗しました。",
            copyResultTemplate: "▼Playポイント計算結果▼\n目標ステータス： {status}\n必要な課金額の目安： 約{yen}{symbol}\n\n計算元：Playポイント計算機 ( {url} )",
            tweetTextMain: "【Playポイント計算機で試算】\n私の目標「{status}」まで、あと【{yen}{symbol}】必要みたい！💰",
            tweetTextReverse: "【Playポイント計算機で試算】\n{yen}{symbol}使うと、約 {points}ポイント 獲得できるみたい！✨"
        }
    },
    'US': {
        lang: "en",
        statuses: { "Bronze": 1.0, "Silver": 1.1, "Gold": 1.2, "Platinum": 1.4, "Diamond": 1.6 },
        statusRates: { 1.0: 1.0, 1.1: 1.1, 1.2: 1.2, 1.4: 1.4, 1.6: 1.6 },
        thresholds: { "Silver": 150, "Gold": 600, "Platinum": 3000, "Diamond": 10000 },
        statusPointsMapping: { 1.0: ["Silver", "Gold", "Platinum", "Diamond"], 1.1: ["Gold", "Platinum", "Diamond"], 1.2: ["Platinum", "Diamond"], 1.4: ["Diamond"], 1.6: [] },
        currencySymbol: "USD",
        rateUnit: "$1",
        tooltips: {
            'tooltip-current-status': `<strong>How to check your current status:</strong><ol><li>Open the Google Play Store.</li><li>Tap your profile icon in the top right.</li><li>Select "Play Points".</li></ol><hr><p>Note: The base points rate is automatically filled based on your status.</p>`,
            'tooltip-target-status': `<strong>Level-up requirements:</strong><ul><li><strong>Silver:</strong> 150+ pts</li><li><strong>Gold:</strong> 600+ pts</li><li><strong>Platinum:</strong> 3,000+ pts</li><li><strong>Diamond:</strong> 10,000+ pts</li></ul><hr><p>※Points accumulate from Jan 1st to Dec 31st. Once you reach the threshold, you level up immediately (valid until the end of the next year).</p>`,
            'tooltip-needed-points': `<strong>How to check points needed:</strong><ol><li>Go to the "Play Points" screen in the Google Play Store.</li><li>Enter the number shown in "XX pts to next level".</li></ol><hr><p>※The Play Points annual cycle ends on Dec 31st. Therefore, the "monthly average" is calculated based on the remaining months until the end of December.</p>`,
            'tooltip-base-rate': `<strong>About base points rate:</strong><p>The base rate according to your current status is automatically entered.</p><p>If you are using an app-specific point boost campaign, please edit this value directly.</p><hr><p><strong>Note:</strong><br>The calculator will automatically use whichever is higher: this value or the rate calculated from the "Campaign Multiplier".</p>`,
            'tooltip-multiplier': `<strong>About campaign multiplier:</strong><p>Enter the multiplier for point boost campaigns, such as those held on weekends.</p><p>Example: Gold (1.2 pts) × <strong>3x</strong> = 3.6 pts</p><hr><p><strong>Note:</strong><br>The calculator will automatically use whichever is higher: the rate calculated with this multiplier or the "Base points rate" value.</p>`,
            'tooltip-amount-yen': `<strong>Calculate points earned:</strong><p>Simulate how many points you can earn from the amount you spend.</p>`,
            'tooltip-reverse-status': `<strong>Base points rate per status:</strong><ul><li><strong>Bronze:</strong> 1.0 pt / $1</li><li><strong>Silver:</strong> 1.1 pts / $1</li><li><strong>Gold:</strong> 1.2 pts / $1</li><li><strong>Platinum:</strong> 1.4 pts / $1</li><li><strong>Diamond:</strong> 1.6 pts / $1</li></ul>`
        },
        uiText: {
            title: "Play Point Calculator - Google Play Points | How much to level up?", mainTitle: "Play Points Calculator",
            siteDescription: "Calculate how much you need to spend to reach your goal status!<br>Also, calculate how many points you can earn from your spending!",
            tabMain: "Standard", tabReverse: "Reverse", tabDiary: "Weekly Awards Diary",
            sectionTitleStatus: "Status Input", labelCurrentStatus: "Current Status",
            labelTargetStatus: "Target Status", labelNeededPoints: "Points to Next Level",
            neededPointsPlaceholder: "e.g., 125", sectionTitleRate: "Points Rate Setting",
            labelBaseRate: "Base points per $1", labelMultiplier: "Campaign Multiplier (e.g., 3x)", labelMultiplierReverse: "Campaign Multiplier",
            warningRate: "*Note: The higher of the input value or (Status x Multiplier) will be automatically applied.",
            calculateButton: "Calculate Amount", copyButton: "Copy", tweetButton: "Share on X",
            sectionTitleReverse: "Reverse Mode", labelAmountYen: "Amount Spent (USD)",
            amountYenPlaceholder: "e.g., 50", reverseCalculateButton: "Calculate Points",
            nextTargetNone: "No further levels", errorInput: "Please enter valid numbers and select a target status.",
            errorNeededPoints: "Please enter a valid number for points to next level.",
            errorTargetStatus: "Please select a target status.",
            errorRate: "The effective rate for calculation is zero or less.", errorMonth: "Failed to calculate remaining months in this year.",
            errorInputReverse: "Please enter a valid number.", errorRateReverse: "The effective rate for calculation is zero or less.",
            errorTargetConsistency: "The points-to-goal value is not valid for the selected target status.",
            resultLabelNeededPoints: "Points to goal", resultLabelTotalYen: "Estimated total spending",
            resultLabelMonthlyYen: "Monthly average", resultLabelMonths: "months",
            resultLabelRate: "Effective rate", resultLabelEarnedPoints: "Estimated points earned",
            perMonth: "/month",
            calculationNote: "*Estimated target spending evenly split by the remaining <b>{months} months</b> until the Google Play Points rank calculation period ends (December 31st each year).",
            yearSuffix: "", monthNames: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
            weekLabel: "Week", weekSuffix: "", pointsPlaceholder: "Points", saveButton: "Save",
            monthlySummaryTitle: "Monthly Summary", yearlySummaryTitle: "Yearly Summary",
            totalLabel: "Total:", averageLabel: "Average:", pointsUnit: "pts", perWeekUnit: "pts/week",
            guestNotice: "[!] Right now, your diary records are saved only in this browser. If you clear cache or browsing data, the records may be lost. In the future, we are considering a member feature to store data on the server — please look forward to it!",
            prizeOptions: ["No Prize", "Mouse", "Earbuds", "Other"],
            noWeeksMessage: "No applicable weeks in this month.",
            backupTitle: "Backup & Restore Data",
            exportBtn: "Export Data (Copy)",
            importBtn: "Import Data (Restore)",
            confirmImportBtn: "Execute Restore",
            backupPlaceholder: "Paste your exported data here",
            exportSuccess: "Copied diary data to clipboard! Please save it in a safe place.",
            importSuccess: "Diary data restored successfully!",
            importError: "Failed to import data. Please check if the data format is correct.",
            fridayReminderText: "It's Friday! Let's claim your Weekly Reward and record it in your diary!",
            reminderTitle: "Friday Reward Notification (Calendar)",
            reminderDesc: "You can set up a weekly recurring reminder for the Weekly Reward. Prevent missing your weekly points and make logging a habit!",
            btnGoogleCal: "Add to Google Calendar",
            btnICal: "Add to Calendar App (iCal)",
            linkArticles: { text: "📝 Articles", href: "blog/" },
            linkKatakata: { text: "🧪 KatakataLab", href: "https://katakatalab.com/" },
            linkPrivacy: { text: "Privacy Policy", href: "privacy.html" },
            linkTerms: { text: "Terms of Service", href: "terms.html" },
            linkQA: { text: "Q&A & Afterword", href: "info.html" },
            linkFeedback: { text: "Feedback", href: "https://docs.google.com/forms/d/e/1FAIpQLSe0HDPLt-jfNXuiGmJ3gxlxUtgeGJ5-AM16Bz2yNw5bk3irNw/viewform?usp=dialog" },
            linkAbout: { text: "What are Play Points?", href: "about-playpoints.html" },
            linkDiscount: { text: "💡 Discount Guide", href: "articles/2026-06-20-discount-gift-cards.html" },
            linkAuthor: { text: "Operator & Policy", href: "author/katakata.html" },
            linkAttention: { text: "⚠️ Country Diff", href: "attention.html" },
            toastCopySuccess: "Copied to clipboard!",
            toastCopyError: "Failed to copy.",
            copyResultTemplate: "▼Play Points Calculation Result▼\nTarget Status: {status}\nEstimated Spending: Approx. {yen} {symbol}\n\nSource: Play Points Calculator ( {url} )",
            tweetTextMain: "[Play Points Calculator]\nI need approx. {yen} {symbol} to reach my goal \"{status}\"! 💰",
            tweetTextReverse: "[Play Points Calculator]\nIf I spend {yen} {symbol}, I can earn approx. {points} points! ✨"
        }
    },
    'KR': {
        lang: "ko",
        statuses: { "브론즈": 1.0, "실버": 1.1, "골드": 1.3, "플래티넘": 1.6, "다이아몬드": 2.0 },
        statusRates: { 1.0: 1.0, 1.1: 1.1, 1.3: 1.3, 1.6: 1.6, 2.0: 2.0 },
        thresholds: { "실버": 150, "골드": 600, "플래티넘": 2400, "다이아몬드": 15000 },
        statusPointsMapping: { 1.0: ["실버", "골드", "플래티넘", "다이아몬드"], 1.1: ["골드", "플래티넘", "다이아몬드"], 1.3: ["플래티넘", "다이아몬드"], 1.6: ["다이아몬드"], 2.0: [] },
        currencySymbol: "₩",
        rateUnit: "1,000₩",
        tooltips: {
            'tooltip-current-status': `<strong>【현재 등급 확인 방법】</strong><ol><li>Google Play 스토어를 엽니다.</li><li>우측 상단의 프로필 아이콘을 누릅니다.</li><li>'Play 포인트'를 선택합니다.</li></ol><hr><p>※등급에 따라 기본 적립률이 자동으로 입력됩니다.</p>`,
            'tooltip-target-status': `<strong>【등급 달성 조건】</strong><ul><li><strong>실버:</strong> 150 pt 이상</li><li><strong>골드:</strong> 600 pt 이상</li><li><strong>플래티넘:</strong> 2,400 pt 이상</li><li><strong>다이아몬드:</strong> 15,000 pt 이상</li></ul><hr><p>※포인트는 매년 1월 1일~12월 31일 동안 누적되며, 조건 달성 시 즉시 등급이 올라갑니다(유효기간은 다음 해 말까지).</p>`,
            'tooltip-needed-points': `<strong>【필요 포인트 확인 방법】</strong><ol><li>Google Play 스토어의 'Play 포인트' 화면을 엽니다.</li><li>화면에 표시되는 '다음 등급까지 ◯◯ pt'의 숫자를 그대로 입력해 주세요.</li></ol><hr><p>※등급 산정 기간은 매년 12월 31일까지이므로, 계산 결과의 '월 평균'은 12월 말까지의 남은 개월 수로 나눈 기준입니다.</p>`,
            'tooltip-base-rate': `<strong>【기본 적립 포인트 정보】</strong><p>현재 등급에 따른 기본 적립률이 자동으로 입력됩니다.</p><p>특정 앱 한정 포인트 증량 이벤트 등을 이용하시는 경우, 이 수치를 직접 편집해 주세요.</p><hr><p><strong>※주의</strong><br>이 값과 '이벤트 배율'로 계산한 값을 비교하여, <strong>더 높은 쪽</strong>이 자동으로 적용됩니다.</p>`,
            'tooltip-multiplier': `<strong>【이벤트 배율 정보】</strong><p>주말 등에 진행되는 포인트 증량 이벤트 배율을 입력합니다.</p><p>예: 골드(1.3pt) × <strong>3배</strong> = 3.9pt</p><hr><p><strong>※주의</strong><br>이 배율로 계산한 값과 '기본 적립 포인트'를 비교하여, <strong>더 높은 쪽</strong>이 자동으로 적용됩니다.</p>`,
            'tooltip-amount-yen': `<strong>【적립 포인트 계산】</strong><p>입력한 금액으로 획득 가능한 포인트를 시뮬레이션합니다.</p>`,
            'tooltip-reverse-status': `<strong>등급별 기본 적립률:</strong><ul><li><strong>브론즈:</strong> 1.0 pt / 1,000₩</li><li><strong>실버:</strong> 1.1 pt / 1,000₩</li><li><strong>골드:</strong> 1.3 pt / 1,000₩</li><li><strong>플래티넘:</strong> 1.6 pt / 1,000₩</li><li><strong>다이아몬드:</strong> 2.0 pt / 1,000₩</li></ul>`
        },
        uiText: {
            title: "구글 플레이 포인트 계산기 - Play Point Calculator | 등급 업까지 얼마 남았지?", mainTitle: "구글 플레이 포인트 계산기",
            siteDescription: "현재 등급에서 목표 등급까지 필요한 결제 금액을 계산할 수 있습니다!<br>결제 금액으로 획득할 수 있는 포인트도 계산 가능합니다!",
            tabMain: "일반 계산", tabReverse: "역산 모드", tabDiary: "주간 리워드 일기",
            sectionTitleStatus: "등급 입력", labelCurrentStatus: "현재 등급",
            labelTargetStatus: "목표 등급", labelNeededPoints: "목표까지 필요한 포인트",
            neededPointsPlaceholder: "예: 120", sectionTitleRate: "적립 설정",
            labelBaseRate: "1,000₩당 기본 적립 포인트", labelMultiplier: "이벤트 배율 (예: 3배)", labelMultiplierReverse: "이벤트 배율",
            warningRate: "*포인트 증량/배율 주의:<br>계산 시 입력값과 (등급별 기본 적립률 x 배율)을 비교하여 더 유리한 쪽이 자동 적용됩니다 (중복 불가)",
            calculateButton: "결제 금액 계산", copyButton: "복사하기", tweetButton: "결과를 X에 공유",
            sectionTitleReverse: "역산 모드", labelAmountYen: "결제 금액 (₩)",
            amountYenPlaceholder: "예: 50000", reverseCalculateButton: "포인트 계산",
            nextTargetNone: "다음 목표 등급이 없습니다", errorInput: "올바른 숫자를 입력하고 목표 등급을 선택해 주세요",
            errorNeededPoints: "목표까지 필요한 포인트에 올바른 숫자를 입력해 주세요",
            errorTargetStatus: "목표 등급을 선택해 주세요",
            errorRate: "계산에 사용되는 적립률이 0 이하입니다", errorMonth: "올해 남은 기간 계산에 실패했습니다",
            errorInputReverse: "올바른 숫자를 입력해 주세요", errorRateReverse: "계산에 사용되는 적립률이 0 이하입니다",
            errorTargetConsistency: "입력한 필요 포인트가 선택한 목표 등급에 대해 올바르지 않습니다.",
            resultLabelNeededPoints: "목표까지 필요한 포인트", resultLabelTotalYen: "총 예상 결제 금액",
            resultLabelMonthlyYen: "월 평균 기준", resultLabelMonths: "개월",
            resultLabelRate: "적용 적립률", resultLabelEarnedPoints: "예상 적립 포인트",
            perMonth: "/월",
            calculationNote: "*Google Play 포인트 등급 산정 기간(매년 12월 31일)까지 남은 <b>{months}개월</b> 동안 균등하게 나눈 목표 결제 금액의 기준입니다.",
            yearSuffix: "년", monthNames: ["1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월"],
            weekLabel: "제", weekSuffix: "주", pointsPlaceholder: "포인트", saveButton: "저장",
            monthlySummaryTitle: "월간 합계", yearlySummaryTitle: "연간 합계",
            totalLabel: "합계:", averageLabel: "평균:", pointsUnit: "pt", perWeekUnit: "pt/주",
            guestNotice: "[!] 현재 이 일기 기록은 브라우저 내에만 저장됩니다. 캐시 삭제 등으로 사라질 수 있으니 주의해 주세요.",
            prizeOptions: ["경품 없음", "마우스", "이어폰", "기타"],
            noWeeksMessage: "이 달에는 대상 주가 없습니다.",
            backupTitle: "데이터 백업 및 복원",
            exportBtn: "데이터 내보내기 (복사)",
            importBtn: "데이터 가져오기 (복원)",
            confirmImportBtn: "복원 실행",
            backupPlaceholder: "내보낸 데이터를 여기에 붙여넣어 주세요",
            exportSuccess: "일기 데이터를 클립보드에 복사했습니다! 안전한 곳에 저장해 주세요.",
            importSuccess: "일기 데이터를 복원했습니다!",
            importError: "데이터 가져오기에 실패했습니다. 데이터 형식을 확인해 주세요.",
            fridayReminderText: "오늘은 금요일! 이번 주 주간 리워드를 받고 일기에 기록합시다!",
            reminderTitle: "금요 리워드 알림 (캘린더)",
            reminderDesc: "매주 금요일에 주간 리워드를 확인하도록 리마인더를 등록할 수 있습니다.",
            btnGoogleCal: "Google 캘린더 등록",
            btnICal: "캘린더 앱 (iCal) 등록",
            linkArticles: { text: "📝 가이드 목록", href: "blog/" },
            linkKatakata: { text: "🧪 KatakataLab", href: "https://katakatalab.com/" },
            linkPrivacy: { text: "개인정보처리방침", href: "privacy.html" },
            linkTerms: { text: "이용약관", href: "terms.html" },
            linkQA: { text: "Q&A 및 후기", href: "info.html" },
            linkFeedback: { text: "의견 제안", href: "https://docs.google.com/forms/d/e/1FAIpQLSe0HDPLt-jfNXuiGmJ3gxlxUtgeGJ5-AM16Bz2yNw5bk3irNw/viewform?usp=dialog" },
            linkAbout: { text: "Play 포인트란?", href: "about-playpoints.html" },
            linkDiscount: { text: "💡 할인 가이드", href: "articles/2026-06-20-discount-gift-cards.html" },
            linkAuthor: { text: "운영자 및 정책", href: "author/katakata.html" },
            linkAttention: { text: "⚠️ 국가별 차이", href: "attention.html" },
            toastCopySuccess: "클립보드에 복사되었습니다!",
            toastCopyError: "복사에 실패했습니다.",
            copyResultTemplate: "▼Play 포인트 계산 결과▼\n목표 등급: {status}\n예상 결제 금액: 약 {yen}{symbol}\n\n출처: 플레이 포인트 계산기 ( {url} )",
            tweetTextMain: "【구글 플레이 포인트 계산기】\n내 목표 「{status}」 등급까지 약 【{yen}{symbol}】 더 필요하네요! 💰",
            tweetTextReverse: "【구글 플레이 포인트 계산기】\n{yen}{symbol} 결제하면 약 {points}포인트 적립되네요! ✨"
        }
    },
    'TW': {
        lang: "zh-TW",
        statuses: { "銅級": 1.0, "銀級": 1.25, "金級": 1.5, "白金級": 1.75, "鑽石級": 2.0 },
        statusRates: { 1.0: 1.0, 1.25: 1.25, 1.5: 1.5, 1.75: 1.75, 2.0: 2.0 },
        thresholds: { "銀級": 250, "金級": 1000, "白金級": 4000, "鑽石級": 15000 },
        statusPointsMapping: { 1.0: ["銀級", "金級", "白金級", "鑽石級"], 1.25: ["金級", "白金級", "鑽石級"], 1.5: ["白金級", "鑽石級"], 1.75: ["鑽石級"], 2.0: [] },
        currencySymbol: "NT$",
        rateUnit: "30元",
        tooltips: {
            'tooltip-current-status': `<strong>【如何確認目前的等級】</strong><ol><li>開啟 Google Play 商店。</li><li>點擊右上角的個人資料圖示。</li><li>選擇「Play Points」。</li></ol><hr><p>※系統會根據您的等級自動填入基本回饋率。</p>`,
            'tooltip-target-status': `<strong>【各等級達成條件】</strong><ul><li><strong>銀級:</strong> 250 pt 以上</li><li><strong>金級:</strong> 1,000 pt 以上</li><li><strong>白金級:</strong> 4,000 pt 以上</li><li><strong>鑽石級:</strong> 15,000 pt 以上</li></ul><hr><p>※點數於每年1月1日至12月31日期間累積，達到目標點數時將立即升級（有效期限至翌年末）。</p>`,
            'tooltip-needed-points': `<strong>【如何確認所需點數】</strong><ol><li>開啟 Google Play 商店的「Play Points」畫面。</li><li>輸入畫面上顯示的「距離下一等級還差 ◯◯ pt」的數字。</li></ol><hr><p>※Play Points 每年結算至12月31日為止，因此計算結果的「月平均」是依據至12月底前的剩餘月份平均計算的參考值。</p>`,
            'tooltip-base-rate': `<strong>【關於基本回饋點數】</strong><p>系統會自動輸入符合您目前等級的基本回饋率。</p><p>如果您使用的是特定應用程式限定的點數加倍活動，請直接修改此數值。</p><hr><p><strong>※請注意</strong><br>計算時會比較此輸入值與「活動倍率」計算後的值，並自動採用<strong>較優惠者</strong>。</p>`,
            'tooltip-multiplier': `<strong>【關於活動倍率】</strong><p>輸入週末等舉辦的點數加倍活動倍率。</p><p>例如：金級(1.5pt) × <strong>3倍</strong> = 4.5pt</p><hr><p><strong>※請注意</strong><br>計算時會比較此倍率計算後的值與「基本回饋點數」，並自動採用<strong>較優惠者</strong>。</p>`,
            'tooltip-amount-yen': `<strong>【計算獲得點數】</strong><p>模擬輸入金額可獲得的預估點數。</p>`,
            'tooltip-reverse-status': `<strong>各等級基本回饋率:</strong><ul><li><strong>銅級:</strong> 1.0 pt / 30元</li><li><strong>銀級:</strong> 1.25 pt / 30元</li><li><strong>金級:</strong> 1.5 pt / 30元</li><li><strong>白金級:</strong> 1.75 pt / 30元</li><li><strong>鑽石級:</strong> 2.0 pt / 30元</li></ul>`
        },
        uiText: {
            title: "Google Play 點數計算器 - Play Point Calculator | 距離升級還差多少？", mainTitle: "Google Play 點數計算器",
            siteDescription: "可以計算從目前等級達到目標等級所需的消費金額！<br>還能計算消費金額可獲得的預估點數！",
            tabMain: "一般計算", tabReverse: "逆算模式", tabDiary: "每週獎勵日記",
            sectionTitleStatus: "輸入等級", labelCurrentStatus: "目前等級",
            labelTargetStatus: "目標等級", labelNeededPoints: "距離目標所需點數",
            neededPointsPlaceholder: "例如：125", sectionTitleRate: "回饋設定",
            labelBaseRate: "每30元的基本回饋點數", labelMultiplier: "活動倍率（例如：3倍）", labelMultiplierReverse: "活動倍率",
            warningRate: "*關於點數加倍/倍率：<br>計算時，會比較輸入值與（等級x倍率），自動套用較有利者（不可併用）",
            calculateButton: "計算消費金額", copyButton: "複製", tweetButton: "分享至 X",
            sectionTitleReverse: "逆算模式", labelAmountYen: "消費金額 (NT$)",
            amountYenPlaceholder: "例如：1500", reverseCalculateButton: "計算點數",
            nextTargetNone: "無下一目標等級", errorInput: "請輸入有效數值並選擇目標等級",
            errorNeededPoints: "請在距離目標所需點數中輸入有效數值",
            errorTargetStatus: "請選擇目標等級",
            errorRate: "用於計算的回饋率必須大於0", errorMonth: "計算今年剩餘月份失敗",
            errorInputReverse: "請輸入有效數值", errorRateReverse: "用於計算的回饋率必須大於0",
            errorTargetConsistency: "輸入的所需點數與選擇的目標等級不符，請確認數值。",
            resultLabelNeededPoints: "距離目標所需點數", resultLabelTotalYen: "預估總消費金額",
            resultLabelMonthlyYen: "月平均參考", resultLabelMonths: "個月",
            resultLabelRate: "適用回饋率", resultLabelEarnedPoints: "預估獲得點數",
            perMonth: "/月",
            calculationNote: "*此預估金額是以 Google Play 點數計算期間（每年12月31日）為止剩餘的 <b>{months}個月</b> 均分計算的參考值。",
            yearSuffix: "年", monthNames: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
            weekLabel: "第", weekSuffix: "週", pointsPlaceholder: "點數", saveButton: "儲存",
            monthlySummaryTitle: "月度統計", yearlySummaryTitle: "年度統計",
            totalLabel: "合計:", averageLabel: "平均:", pointsUnit: "pt", perWeekUnit: "pt/週",
            guestNotice: "[!] 目前此日記記錄僅儲存在瀏覽器中。清除快取可能會導致資料遺失，敬請注意。",
            prizeOptions: ["無獎品", "滑鼠", "耳機", "其他"],
            noWeeksMessage: "此月份無適用週數。",
            backupTitle: "資料備份與還原",
            exportBtn: "匯出資料 (複製)",
            importBtn: "匯入資料 (還原)",
            confirmImportBtn: "執行還原",
            backupPlaceholder: "請將匯出的資料貼至此處",
            exportSuccess: "已將日記資料複製到剪貼簿！請妥善保存。",
            importSuccess: "日記資料已順利還原！",
            importError: "資料匯入失敗，請檢查格式是否正確。",
            fridayReminderText: "今天是星期五！快來領取本週每週獎勵並記錄在日記中吧！",
            reminderTitle: "週五獎勵提醒 (日曆)",
            reminderDesc: "您可以設定每週五提醒您領取每週獎勵，避免錯過點數。",
            btnGoogleCal: "新增至 Google 日曆",
            btnICal: "新增至日曆 App (iCal)",
            linkArticles: { text: "📝 指南列表", href: "blog/" },
            linkKatakata: { text: "🧪 KatakataLab", href: "https://katakatalab.com/" },
            linkPrivacy: { text: "隱私權政策", href: "privacy.html" },
            linkTerms: { text: "服務條款", href: "terms.html" },
            linkQA: { text: "Q&A 與後記", href: "info.html" },
            linkFeedback: { text: "意見回饋", href: "https://docs.google.com/forms/d/e/1FAIpQLSe0HDPLt-jfNXuiGmJ3gxlxUtgeGJ5-AM16Bz2yNw5bk3irNw/viewform?usp=dialog" },
            linkAbout: { text: "什麼是 Play Points？", href: "about-playpoints.html" },
            linkDiscount: { text: "💡 折扣指南", href: "articles/2026-06-20-discount-gift-cards.html" },
            linkAuthor: { text: "營運者與政策", href: "author/katakata.html" },
            linkAttention: { text: "⚠️ 國家別差異", href: "attention.html" },
            toastCopySuccess: "已複製至剪貼簿！",
            toastCopyError: "複製失敗。",
            copyResultTemplate: "▼Play Points 計算結果▼\n目標等級： {status}\n預估消費金額： 約{yen}{symbol}\n\n計算來源：Play Points 計算器 ( {url} )",
            tweetTextMain: "【Google Play 點數計算器】\n距離我的目標「{status}」還需要【{yen}{symbol}】！💰",
            tweetTextReverse: "【Google Play 點數計算器】\n消費 {yen}{symbol} 大約可以獲得 {points} 點！✨"
        }
    }
};

CONFIGS.JP.tooltips['tooltip-reverse-base-rate'] = CONFIGS.JP.tooltips['tooltip-base-rate'];
CONFIGS.JP.tooltips['tooltip-reverse-multiplier'] = CONFIGS.JP.tooltips['tooltip-multiplier'];
CONFIGS.US.tooltips['tooltip-reverse-base-rate'] = CONFIGS.US.tooltips['tooltip-base-rate'];
CONFIGS.US.tooltips['tooltip-reverse-multiplier'] = CONFIGS.US.tooltips['tooltip-multiplier'];
CONFIGS.KR.tooltips['tooltip-reverse-base-rate'] = CONFIGS.KR.tooltips['tooltip-base-rate'];
CONFIGS.KR.tooltips['tooltip-reverse-multiplier'] = CONFIGS.KR.tooltips['tooltip-multiplier'];
CONFIGS.TW.tooltips['tooltip-reverse-base-rate'] = CONFIGS.TW.tooltips['tooltip-base-rate'];
CONFIGS.TW.tooltips['tooltip-reverse-multiplier'] = CONFIGS.TW.tooltips['tooltip-multiplier'];

export const STATE = {
    currentRegion: 'JP',
    dom: {},
    diaryState: {
        currentYear: new Date().getFullYear(),
        currentMonth: new Date().getMonth() + 1,
    }
};

// 互換性マウント
if (typeof window !== 'undefined' && window.__TEST_ENV__) {
    window.PP_APP = window.PP_APP || {};
    window.PP_APP.ANALYTICS = ANALYTICS;
    window.PP_APP.CONSTANTS = CONSTANTS;
    window.PP_APP.CONFIGS = CONFIGS;
    window.PP_APP.STATE = STATE;
}
