'use strict';
const assert=require('node:assert/strict'); const fs=require('node:fs'); const path=require('node:path'); const test=require('node:test');
const root=path.resolve(__dirname,'..'); const read=p=>fs.readFileSync(path.join(root,p),'utf8');
test('Google Play特別獲得率をランク通常率へ掛けない',()=>{const c=read('js/calculator.js');assert.match(c,/const promotionRate = multiplier/);assert.match(c,/Math\.max\(directRate, promotionRate\)/);assert.doesNotMatch(c,/statusRate \* multiplier/);});
test('Consent Modeは広告用途をPurpose 1だけで一括許可しない',()=>{const c=read('js/consent.js');assert.match(c,/consents\[3\]/);assert.match(c,/consents\[4\]/);assert.match(c,/ad_user_data: personalizedAdsAllowed/);assert.match(c,/ad_personalization: personalizedAdsAllowed/);});
test('ゲーム生成物は確認範囲と出典を明示し保留記事を推薦しない',()=>{const g=read('scripts/generate-game-simulators.cjs');assert.match(g,/game-source-section/);assert.match(g,/game prices/pity are reference values/);assert.ok(!g.includes('tgs-google-play-vip.html'));assert.ok(!g.includes('diamond-valley-festival-guide.html'));});
test('楽天還元率を固定の5〜15%以上と断定しない',()=>{for(const p of ['scripts/insert-lp-monetization.cjs','status/gold/index.html','campaign/3x/index.html'])assert.ok(!read(p).includes('実質5%〜15%以上'),p);});
test('法務ページの更新日は2026-08-18へ統一',()=>{for(const p of ['privacy.html','terms.html']){const h=read(p);assert.match(h,/last-modified" content="2026-08-18/);assert.match(h,/dateModified": "2026-08-18/);assert.match(h,/最終改定日：<\/strong>2026-08-18/);}});
test('CSPはHTML属性のinline scriptを禁止する',()=>{assert.match(read('.htaccess'),/script-src-attr 'none'/);});
test('ブラウザCIはゲームと記事の収益経路を検査する',()=>{const w=read('.github/workflows/browser-smoke.yml');assert.match(w,/browser-revenue-smoke\.cjs/);const s=read('.github/scripts/browser-revenue-smoke.cjs');assert.match(s,/games\/genshin/);assert.match(s,/article-ad-container/);});
test('ゲームサイトマップはコンテンツ日付台帳を参照する',()=>{const s=read('scripts/sitemap-sync.cjs');assert.match(s,/CONTENT_DATE_OVERRIDES\[relativePath\]/);assert.match(s,/htmlDateFor/);assert.match(read('scripts/generate-game-simulators.cjs'),/last-modified/);});
