from pathlib import Path


def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if new in text:
        return False
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{path}: expected one match, found {count}: {old[:120]!r}')
    p.write_text(text.replace(old, new, 1), encoding='utf-8')
    return True


replace_once(
    'js/share.js',
    """    buildRewardShareUrl(points, prize) {\n        const lang = STATE.currentRegion || 'ja';\n        const numPoints = Number.parseInt(points, 10);\n        const validPoints = Number.isFinite(numPoints) && numPoints >= 0 ? numPoints : 0;\n        const siteUrl = 'https://playpoint-sim.com/';\n\n        let tweetText = '';\n        if (lang === 'en') {\n            tweetText = `Got ${validPoints} Play Points from this week's Google Play Weekly Prize! 🎉 #GooglePlay #PlayPoints #PlayPointCalc`;\n        } else if (lang === 'ko') {\n            tweetText = `이번 주 Google Play 주간 혜택으로 ${validPoints}pt를 받았습니다! 🎉 #구글플레이 #플레이포인트 #PlayPoint계산기`;\n        } else if (lang === 'tw') {\n            tweetText = `這週的 Google Play 每週獎勵抽到了 ${validPoints} 點！🎉 #GooglePlay #Play點數 #PlayPoint計算器`;\n        } else {\n            tweetText = `今週のGoogle Playウィークリーリワードは【${validPoints}pt】でした！🎉 #Playポイント #GooglePlay #Playポイント計算機`;\n        }\n\n        const shareUrl = new URL('https://twitter.com/intent/tweet');\n        shareUrl.searchParams.set('text', tweetText);\n        shareUrl.searchParams.set('url', siteUrl);\n        return shareUrl.toString();\n    },\n""",
    """    buildRewardShareUrl(points, prize) {\n        const region = STATE.currentRegion || 'JP';\n        const numPoints = Number.parseInt(points, 10);\n        const validPoints = Number.isFinite(numPoints) && numPoints >= 0 ? numPoints : 0;\n        const regionPaths = { JP: '', US: 'en/', KR: 'ko/', TW: 'tw/', HK: 'hk/', IN: 'in/' };\n        const siteUrl = new URL(regionPaths[region] || '', 'https://playpoint-sim.com/').toString();\n\n        let tweetText = '';\n        if (region === 'US' || region === 'IN') {\n            tweetText = `Got ${validPoints} Play Points from this week's Google Play Weekly Prize! 🎉 #GooglePlay #PlayPoints #PlayPointCalc`;\n        } else if (region === 'KR') {\n            tweetText = `이번 주 Google Play 주간 혜택으로 ${validPoints}pt를 받았습니다! 🎉 #구글플레이 #플레이포인트 #PlayPoint계산기`;\n        } else if (region === 'TW' || region === 'HK') {\n            tweetText = `這週的 Google Play 每週獎勵抽到了 ${validPoints} 點！🎉 #GooglePlay #Play點數 #PlayPoint計算器`;\n        } else {\n            tweetText = `今週のGoogle Playウィークリーリワードは【${validPoints}pt】でした！🎉 #Playポイント #GooglePlay #Playポイント計算機`;\n        }\n\n        const shareUrl = new URL('https://twitter.com/intent/tweet');\n        shareUrl.searchParams.set('text', tweetText);\n        shareUrl.searchParams.set('url', siteUrl);\n        return shareUrl.toString();\n    },\n"""
)

replace_once(
    '.github/scripts/browser-smoke.cjs',
    """  { key: 'JP', path: '', locale: 'ja-JP', title: 'Google Play Points 計算機', button: '課金額を計算' },\n  { key: 'US', path: 'en/', locale: 'en-US', title: 'Google Play Points Calculator', button: 'Calculate amount' },\n  { key: 'KR', path: 'ko/', locale: 'ko-KR', title: 'Google Play Points 계산기', button: '결제 금액 계산' },\n  { key: 'TW', path: 'tw/', locale: 'zh-TW', title: 'Google Play Points 計算器', button: '計算消費金額', shareRestore: { status: '1.25', target: 'gold', expected: '金級' } },\n  { key: 'HK', path: 'hk/', locale: 'zh-HK', title: 'Google Play Points 計算器（香港）', button: '計算消費金額', statusCount: 5, staticReverseLabel: '每 HK$7 獲得點數（自動帶入，可修改）', gamePath: '/tw/games/', tooltipContains: 'HK$7', tooltipExcludes: 'NT$30', currencyPrefix: 'HK$', calendarPath: '/hk/', shareRestore: { status: '1.25', target: 'gold', expected: '金級' } },\n  { key: 'IN', path: 'in/', locale: 'en-IN', title: 'Google Play Points Calculator — India', button: 'Calculate Amount', statusCount: 4, staticReverseLabel: 'Points per ₹5 (auto-filled, editable)', gamePath: '/en/games/', tooltipContains: '₹5', tooltipExcludes: '$1', currencyPrefix: '₹', calendarPath: '/in/', shareRestore: { status: '1.1', target: 'gold', expected: 'Gold' } }\n];""",
    """  { key: 'JP', path: '', locale: 'ja-JP', title: 'Google Play Points 計算機', button: '課金額を計算', rewardPath: '/', rewardText: 'ウィークリーリワード' },\n  { key: 'US', path: 'en/', locale: 'en-US', title: 'Google Play Points Calculator', button: 'Calculate amount', rewardPath: '/en/', rewardText: 'Weekly Prize' },\n  { key: 'KR', path: 'ko/', locale: 'ko-KR', title: 'Google Play Points 계산기', button: '결제 금액 계산', rewardPath: '/ko/', rewardText: '주간 혜택' },\n  { key: 'TW', path: 'tw/', locale: 'zh-TW', title: 'Google Play Points 計算器', button: '計算消費金額', rewardPath: '/tw/', rewardText: '每週獎勵', shareRestore: { status: '1.25', target: 'gold', expected: '金級' } },\n  { key: 'HK', path: 'hk/', locale: 'zh-HK', title: 'Google Play Points 計算器（香港）', button: '計算消費金額', rewardPath: '/hk/', rewardText: '每週獎勵', statusCount: 5, staticReverseLabel: '每 HK$7 獲得點數（自動帶入，可修改）', gamePath: '/tw/games/', tooltipContains: 'HK$7', tooltipExcludes: 'NT$30', currencyPrefix: 'HK$', calendarPath: '/hk/', shareRestore: { status: '1.25', target: 'gold', expected: '金級' } },\n  { key: 'IN', path: 'in/', locale: 'en-IN', title: 'Google Play Points Calculator — India', button: 'Calculate Amount', rewardPath: '/in/', rewardText: 'Weekly Prize', statusCount: 4, staticReverseLabel: 'Points per ₹5 (auto-filled, editable)', gamePath: '/en/games/', tooltipContains: '₹5', tooltipExcludes: '$1', currencyPrefix: '₹', calendarPath: '/in/', shareRestore: { status: '1.1', target: 'gold', expected: 'Gold' } }\n];"""
)

replace_once(
    '.github/scripts/browser-smoke.cjs',
    """    if (locale.calendarPath) assert(decodeURIComponent(header.calendarHref).includes(locale.calendarPath), `${locale.key} calendar link does not point back to ${locale.calendarPath}`);\n\n    await page.locator('#currentStatus').selectOption({ index: 1 });""",
    """    if (locale.calendarPath) assert(decodeURIComponent(header.calendarHref).includes(locale.calendarPath), `${locale.key} calendar link does not point back to ${locale.calendarPath}`);\n\n    const rewardShare = await page.evaluate(async () => {\n      const { SHARE } = await import('/js/share.js');\n      return SHARE.buildRewardShareUrl(123, '');\n    });\n    const rewardIntent = new URL(rewardShare);\n    const rewardSiteUrl = new URL(rewardIntent.searchParams.get('url'));\n    assert(rewardSiteUrl.pathname === locale.rewardPath, `${locale.key} reward share path: ${rewardSiteUrl.pathname}`);\n    assert((rewardIntent.searchParams.get('text') || '').includes(locale.rewardText), `${locale.key} reward share text language mismatch`);\n\n    await page.locator('#currentStatus').selectOption({ index: 1 });"""
)

print('Region-aware weekly reward sharing fix applied or already present.')
